### ISSUE TITLE
There is a problem in reademe file

### ISSUE THREAD

**Issue by lfbdev** [merico-dev/stream#121]
## Describe the Bug

![image](https://user-images.githubusercontent.com/94163234/148877229-0eea016d-a5bd-4150-b4fb-4948f3b180ef.png)

should be apply

**Comment by lfbdev** [comment]
add static check

**Comment by IronCore864** [comment]
- apply/install: fixed in the latest PR
- make fmt/vet: please add in the next PR.

**Comment by IronCore864** [comment]
Add: the doc should mention that `GOPATH/bin` needs to be placed in `PATH` so that `goimports` can work.
