### ISSUE TITLE
GitHub Actions plugin: add support for Python and Nodejs

### ISSUE THREAD

**Issue by IronCore864** [merico-dev/stream#14]
## Description

At the moment, the github actions plugin only can create workflows for Golang. We need to be able to support Python and Nodejs (we use them ourselves, so these two have higher priority than other programming languages).

For Python, maybe we can create some simple workflow like this one:
https://github.com/actions/starter-workflows/blob/a85155b04a1b885de7a5021312303fe5c1cb58e4/ci/python-app.yml
More research in [github actions starter workflows](https://github.com/actions/starter-workflows) is welcome.

For Node, it's a bit more complicated because some use node alone, some use it with webpack, some use it with gulp, etc.
Examples:
- https://github.com/actions/starter-workflows/blob/a85155b04a1b885de7a5021312303fe5c1cb58e4/ci/node.js.yml
- https://github.com/actions/starter-workflows/blob/a85155b04a1b885de7a5021312303fe5c1cb58e4/ci/webpack.yml
- https://github.com/actions/starter-workflows/blob/a85155b04a1b885de7a5021312303fe5c1cb58e4/ci/npm-grunt.yml
Some more research in this repo might help. We might need to add more parameters to the config to support different options.

**Comment by IronCore864** [comment]
Let's try to finish this tomorrow so that we can focus on testing next week and prepare for the v0.0.1 release. @lfbdev @daniel-hutao

**Comment by daniel-hutao** [comment]
> Let's try to finish this tomorrow so that we can focus on testing next week and prepare for the v0.0.1 release. @lfbdev @daniel-hutao

Maybe we need to merge #47 and close #7 first.

**Comment by daniel-hutao** [comment]
#69
