### ISSUE TITLE
devstream.state file created even when "apply" isn't executed.

### ISSUE THREAD

**Issue by IronCore864** [merico-dev/stream#240]
## Describe the Bug

When we run `dtm init`, `dtm version`, or simply `dtm`, the `devstream.state` file is created.

## Expected Behavior

We should only create the state file when we run `dtm apply`; for other commands like `version`, `init` that don't rely on the state file, we don't need to create the file prematurely.

**Comment by daniel-hutao** [comment]
I'll handle this issue.
