### ISSUE TITLE
Proposal: split the config.yaml into more smaller configuration files

### ISSUE THREAD

**Issue by daniel-hutao** [merico-dev/stream#259]
## Description

As you can see, the `config.yaml` is very large now. Any user who uses this configuration needs to delete some plugins that are not needed, otherwise, it will fail with a high probability.

So I suggest keeping only a few simple plugin configurations in `example/config.yaml`, and putting more plugin configurations into separate documents. Finally, the users can choose which plugins to add in. 

In addition, we need to support "multiple configuration files" support, so that the configurations of different plugins can be managed separately, and the probability of errors is smaller.

**Comment by daniel-hutao** [comment]
https://github.com/merico-dev/stream/pull/258#discussion_r818256885

**Comment by IronCore864** [comment]
Moving to our internal Jira.
