### ISSUE TITLE
proposal: need to use `values.yaml` to make more custom configuration for apps installed from helm chart

### ISSUE THREAD

**Issue by imxw** [merico-dev/stream#272]
## Description

some plugins are installed by helm chart, but we can't make some custom configuration now. So please support  it! Let users can configure the apps by `values.yaml`.

**Comment by daniel-hutao** [comment]
Good suggestion! Are you willing to implement this feature? 

If you are willing to do it, I will be very happy to help you if nedded.

**Comment by imxw** [comment]
> 

Yes, I'm happy to  implement it

**Comment by daniel-hutao** [comment]
> Yes, I'm happy to implement it

Cool~
/assign @imxw

**Comment by daniel-hutao** [comment]
1. First of all you can find config examples for all helm-plugins under `docs/plugins/`
2. Then add a parameter under options.chart -> values_yaml: values.yaml
3. Then see the code for more info `pkg/util/helm/param.go:29`
