### ISSUE TITLE
Proposal: integrate openldap plugin

### ISSUE THREAD

**Issue by imxw** [merico-dev/stream#284]
## Description

Most of the DevOps tools used by small and medium-sized companies are open source and have their own user authentication system. If each platform maintains a set of user data, the maintenance workload will increase greatly, so we basically choose a unified authentication system, and [OpenLDAP](https://www.openldap.org/) is a good choice, and it is free and open source. As a DevOps toolchain manager, it is necessary for DevStream to integrate the tool, and I will provide some of my best practices.

**Comment by daniel-hutao** [comment]
Thanks for your contribution.

/assign @imxw
