### ISSUE TITLE
Adding a "planning decision" feature to determine the next action

### ISSUE THREAD

**Issue by daniel-hutao** [merico-dev/stream#29]
## Description

Adding a "action calculation" feature to determine the next **action** based on the current **States** of the environment and the input **Config**.

## Describe the Proposal

When the state management function is integrated into the main branch #28 , we need to use the States in the next step, that is, an algorithm is needed to determine the specific actions each time the **dsm** is executed.

The general idea is as follows:

```go
type ActionFunc func(tool *config.Tool) (bool, error)

type Plan struct {
	Changes []*Change
}

type Change struct {
	Tool   *config.Tool
	Action ActionFunc
}

func MakePlan(smgr statemanager.Manager, cfg config.Config) *Plan {...}

// ......
func TestMakePlan() {
	// ......
	plan := MakePlan(smgr, cfg)
	for _, change := range plan.Changes {
		change.Action(change.Tool)
	}
}
```

**Comment by daniel-hutao** [comment]
/assign @daniel-hutao 

I'll make a pr for this feature after #28 is merged.

**Comment by IronCore864** [comment]
Very good. This is an important feature for our v0.1 release.
