### ISSUE TITLE
proposal: create a cmd tool to help generate scaffolding for plugin code

### ISSUE THREAD

**Issue by daniel-hutao** [merico-dev/stream#325]
## Description

If we need to develop a new plugin, there will be a lot of `repetitive work`. There is a lot of repetitive code. Copy-pasting of this code is tedious and error-prone. So I want to develop a tool to do this.

## Describe the Proposal

cmd eg.

`dtm plugin create --name=your-plugin-name --type=your-plugin-type`

The first version will be: `dtm plugin create --name=you-plugin-name`. But it may be necessary to support the below commands in the future:

- `dtm plugin rename --name=your-plugin-name --new-name=your-new-plugin-name`
- `dtm plugin delete --name=your-plugin-name`
- `dtm plugin create --name=your-plugin-name --type=helm`

---

- I wanna put the template file (tpl) in the `main repo` stream so it can be run offline. And the update will not need to modify multiple repos at the same time. This update will be more frequent than repo-scaffolding plugins, because this structure is closely related to the `dtm` itself, so I think it will be easier to put the tpl stay with `stream`.
- When this `create` command is executed, it will put many of the generated files in the corresponding directory, and then leave a `TODO: xxx` comment in it.
- I'll create a new package `internal/pkg/pluginbuilder` and put all logic inside this pkg(Of course, the entry cmd will still be in the `cmd package`. But inside cmd is just very simple "code").

**Comment by IronCore864** [comment]
A very good proposal.

To me, `dtm plugin create` might mean "create the tool" using that plugin. Similarly, `dtm plugin rename` could mean to rename the local *.so file.

Maybe we can create a more self-explanatory name.

Some random examples: `dtm contributor-helper create-plugin abc` (it's very long, bad example; what I mean by it is, the command can be more specific).

**Comment by daniel-hutao** [comment]
> A very good proposal.
> 
> To me, `dtm plugin create` might mean "create the tool" using that plugin. Similarly, `dtm plugin rename` could mean to rename the local *.so file.
> 
> Maybe we can create a more self-explanatory name.
> 
> Some random examples: `dtm contributor-helper create-plugin abc` (it's very long, bad example; what I mean by it is, the command can be more specific).

Good tips!

I have a new idea about the cmd name:

- `dtm develop create-plugin --name=your-plugin-name`

Some other cmds in the future maybe:

- `dtm develop delete-plugin --name=your-plugin-name`
- `dtm develop create-env`
- `dtm develop lint-xxx`
- ...

**Comment by imxw** [comment]
I like this proposal. Hopefully it will be finished and merged into trunk soon, so I will have more fun writing plugins!
