### ISSUE TITLE
🐞 After I submit a pr, the github action check executes with an error

### ISSUE THREAD

**Issue by summingyu** [merico-dev/stream#338]
## Question

github aciton reports 403 error after "test" under "build-and-test-on-macos"

## Screenshots
https://github.com/merico-dev/stream/runs/5638000058?check_suite_focus=true
![image](https://user-images.githubusercontent.com/17695185/159402602-584ded1c-738d-4f81-97d7-62ab38fbb755.png)

**Comment by daniel-hutao** [comment]
Thanks for your feedback! I'll fix it at a week.

**Comment by daniel-hutao** [comment]
#326
