### ISSUE TITLE
📖 Missing doc for `dtm destroy`

### ISSUE THREAD

**Issue by algobot76** [merico-dev/stream#339]
## Scope

`docs/core_concept.md`

## Describe the Change

- Nitpick: Change the file name from `core_concept.md` to `core_concepts.md`, so that the file name matches the title.
- Add doc about the command `dtm destroy`
- Suggestion: Instead of explaining dtm commands in `core_concept.md`, why not create a separate doc called `dtm_commands_explained.md` which explains what each dtm command does?

## Screenshots

n/a

## Additional Context

n/a

**Comment by IronCore864** [comment]
Thanks @[algobot76] for raising this doc issue!

All solid points, which have been fixed in https://github.com/merico-dev/stream/pull/340

Good job!
