### ISSUE TITLE
Proposal: Refactor All Plugins to Be Consistent with The `Plugin Template`

### ISSUE THREAD

**Issue by daniel-hutao** [merico-dev/stream#342]
## Description

Now we have tools to automatically generate the scaffolding of a plugin. But we haven't before.

Yes, so there must be some inconsistencies in so many plugins that have been implemented before. 

Let me think, how can we fix it?

## How to do it

First, you need to know how we generate a plugin scaffolding now.
You could see the #325 for more info with the command `dtm develop create-plugin --name=foo`.

Of course, you'll need to try running this command locally to see what it scaffold for you. You can see the local changes with the `git` tool. Going a step further, maybe you can take a look at the corresponding source code of `develop` sub-command, maybe all the details you need to know can be obtained this way.

Then, you know what materials a new plugin contains. Yes, the next step is to see how the old plugins differs from the new one and try to make that drift go away.

Of course, the `dtm develop create-plugin --name=foo` command hasn't been practiced, so it's not necessarily right. So, stay skeptical and give feedback if you feel there is anything unreasonable about this command.

## Last but not least

Have fun with refactoring. Don't be shy and tell me if you need help, I'm always there.

**Comment by imxw** [comment]
> 

I'm happy to do that. Just waiting for the distribution of @daniel-hutao

**Comment by daniel-hutao** [comment]
ok，ok，ok，3 volunteers now，，，

**Comment by daniel-hutao** [comment]
@imxw 
- [ ] argocd
- [ ] kube-prometheus
- [ ] jenkins 
- [ ] openldap 
- [ ] githubactions-golang

@warren830 
- [ ] argocdapp
- [ ] devlake
- [ ] trello
- [ ] gitlabci  
- [ ] githubactions-nodejs


@summingyu 
- [ ] github-repo-scaffolding-golang
- [ ] jira-github
- [ ] trello-github
- [ ] githubactions-python

**Comment by daniel-hutao** [comment]
#345
