### ISSUE TITLE
Proposal: Add Homebrew support

### ISSUE THREAD

**Issue by algobot76** [merico-dev/stream#351]
## Description

It is cumbersome to download an executable from GitHub and put it into `/usr/local/bin` whenever a new release comes out. Life would be a lot easier if I could download `dtm` by running `brew install dtm` and upgrade it by running `brew upgrade dtm`.

## Describe the Proposal

Add a new formulae to Homebrew. See https://docs.brew.sh/Adding-Software-to-Homebrew

## Has the Feature been Requested Before?

no

## Describe the Alternatives You Have Considered

n/a

## Additional Context

n/a

**Comment by IronCore864** [comment]
Thanks for this great proposal.

Please hold on for a moment; we probably need to fork homebrew into another org.

**Comment by IronCore864** [comment]
It seems like we can't put devstream to homebrew-core according to: https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae

> Our policy is that formulae in the core tap ([homebrew/core](https://github.com/Homebrew/homebrew-core)) must be open-source with an [Debian Free Software Guidelines license](https://wiki.debian.org/DFSGLicenses)

DevStream has Apache 2.0 license and it seems it's not DFSG-free.

I propose we maintain a new tap: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

For now, please use this one https://github.com/devstream-io/homebrew-devstream and create a PR there. Thanks!

**Comment by algobot76** [comment]
See https://github.com/devstream-io/homebrew-devstream/pull/1

**Comment by IronCore864** [comment]
Brew now is supported from version v0.3.1. Thanks for contributing.
