### ISSUE TITLE
Adding air-gapped installation support.

### ISSUE THREAD

**Issue by daniel-hutao** [merico-dev/stream#36]
## Description

We need to provide a mechanism to support users to use in an air-gapped or a bad network environment.

Maybe we could provider a shell script like `offline-tool.sh` & text file like `resource.txt`. These 2 file could:
1.  `resources.txt` maintain all resources dsm needed when deploy a new env. Users can customize the content of this file to decide that they need to download all or part of the resources.
2.  `offline-tool.sh` can download all resources listed in `resources.txt`

file structure may like below:
stream
- hack/ (or script?)
   - offline-tool.sh
   - resources.txt

**Comment by daniel-hutao** [comment]
@IronCore864 @lfbdev Please take a look at this feature and give some advice here.

**Comment by IronCore864** [comment]
This is a good idea. Let's discuss later.
At the moment, I'm moving this issue to the backlog/roadmap.
Let's commit to the v0.1 release this month.

**Comment by IronCore864** [comment]
This issue is closely related to #23. Closing this one and let's move the discussion there.
