### ISSUE TITLE
Change install command to create/apply

### ISSUE THREAD

**Issue by daniel-hutao** [merico-dev/stream#48]
## Description

Maybe we need to change the install command to create/apply because the uninstall operation can be triggered during the execution of the install command, so the install command is confusing. 

In addition, the delete operation may require more consideration. If the user accidentally specifies an empty configuration file, after executing the `dtm` command, all installed components will be uninstalled, which may not be what they want. We may need to provide a separate command for the uninstall action, such as the `delete` command, to let users know the real result of their command action.

I consider solving the first problem mentioned above first - rename the install command. 
Then modify the `planmanager` so that `create/apply` does not trigger the uninstall action. 
Finally, add a separate `uninstall/delete` command entrance.

/kind proposal
/assign @daniel-hutao 
/cc @merico-dev/devstream

## Done-Done Check

- [ ] interfaces not changed
- [ ] command change to apply and delete
- [ ] document update (readme, etc)

**Comment by IronCore864** [comment]
Right, I think we only need two commands, apply and uninstall:
- apply makes sure the state and the config are the same (uninstall might be triggered);
- uninstall destroys everything from the state no matter what the config is.

I'm moving this to the backlog for now; let's focus on v0.0.1 first. We will revisit this in 2022 Jan.

**Comment by daniel-hutao** [comment]
Ok, Let's discuss it further in 2022 Jan.

**Comment by IronCore864** [comment]
Delete will be implemented in another ticket. Closing this one for now.
