### ISSUE TITLE
reflactor: Create a New `plugin` Package to Store the Code with All the Built-in Plugins

### ISSUE THREAD

**Issue by daniel-hutao** [merico-dev/stream#53]
## Description

I think that we could create a new `plugin` package to store the code with all the built-in plugins and the pluginengine.
The pkg tree now is like below:
```
internal/pkg/
	argocd
	argocdapp
	backend
	configloader
	githubactions
	planmanager
	pluginengine
	pluginmanager
	statemanager
	version
```

The packages with the build-in plugins will be more and more. Maybe putting them under one package will make it clearer. Just like below:

```
internal/pkg/
	plugin/
		argocd
		argocdapp
		githubactions
	backend
	configloader
	planmanager
	pluginengine
	pluginmanager
	statemanager
	version
```

/kind proposal
/cc @merico-dev/devstream

**Comment by IronCore864** [comment]
Good suggestion. This separates the plugins and the dtm components.

Only one comment: maybe use "plugin**s**" (plural instead of singular).

**Comment by IronCore864** [comment]
Will do for v0.1.0 release, but after v0.0.1.

**Comment by daniel-hutao** [comment]
> ...
> * maybe use "plugin**s**" (plural instead of singular)
> ...

Maybe plugin is more standard. See also https://www.k8stech.net/gopl/chapter10/ch10-06/
![image](https://user-images.githubusercontent.com/18692628/147087207-f3e5e2a0-9541-4467-8e68-b9ebd3ddf355.png)
