### ISSUE TITLE
Require Multiple Reviewers for PR

### ISSUE THREAD

**Issue by IronCore864** [merico-dev/stream#65]
## Description

For the main branch, set the number of approving reviews to 2.

**Comment by daniel-hutao** [comment]
Prow is a Kubernetes based CI/CD system. It provides GitHub automation in the form of policy enforcement, chat-ops via `/foo` style commands, and automatic PR merging.

Maybe we clould use Prow to improve DevStream cicd.

See also: https://github.com/kubernetes/test-infra/tree/master/prow#readme

Style like: 

![image](https://user-images.githubusercontent.com/18692628/147401550-49ff1775-2544-43b4-834d-73ef83f9d64d.png)

![image](https://user-images.githubusercontent.com/18692628/147401563-336c3bf1-4263-4e0a-a786-527bb9039899.png)

**Comment by lfbdev** [comment]
we may use this opt:
![image](https://user-images.githubusercontent.com/94163234/148022614-93484362-6259-4f1f-9205-aa4a250a012d.png)

**Comment by lfbdev** [comment]
but normal developers do not have this permission, need @basicthinker's help
