### ISSUE TITLE
bug: githubactions "delete" failed with no "sha" error

### ISSUE THREAD

**Issue by daniel-hutao** [merico-dev/stream#81]
## Describe the Bug

githubactions "delete" failed with no "sha" error

```
2021/12/28 10:42:42 DELETE https://api.github.com/repos/daniel-hutao/animal/contents/.github/workflows/pr-builder.yml: 422 Invalid request.

"sha" wasn't supplied. []
```

## How to Reproduce

uninstall or reinstall a githubaction

## Screenshots

![image](https://user-images.githubusercontent.com/18692628/147522412-711b3508-de35-420f-845c-c188de216dfa.png)

**Comment by daniel-hutao** [comment]
fixed by #76

**Comment by lfbdev** [comment]
reloved,  [need SHA opt ] (https://github.com/merico-dev/stream/pull/76)

**Comment by daniel-hutao** [comment]
It could be closed now. #86
